language: go
sudo: false
go:
  - 1.8.x
  - tip

go_import_path: github.com/go-hackernews

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -t -v ./...
  - chmod +x ./go.test.sh
  

script:
  - ./go.test.sh
  - go test -v -covermode=count -coverprofile=coverage.out
$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
